name: "Calculator Scenario 07"

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Debug'
  projectPath: './samples/Calculator/src/Calculator.Console/Calculator.Console.csproj' # this is specific to example - in most cases not needed

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(projectPath)' # this is specific to example - in most cases not needed
  displayName: 'dotnet restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: '$(projectPath)' # this is specific to example - in most cases not needed
  displayName: 'dotnet build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: "tool"
    arguments: 'install -g dotnet-coverage'
  displayName: 'install dotnet-coverage'

- task: Bash@3
  inputs:
    script: 'dotnet-coverage collect -f cobertura -o report.cobertura.xml "dotnet run --no-build add 10 24"'
    workingDirectory: './samples/Calculator/src/Calculator.Console/' 
  displayName: 'install dotnet-coverage'

- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: ./samples/Calculator/src/Calculator.Console/report.cobertura.xml